# Banco de dados de teste (H2 em memória - precisa da dependência do H2 no pom.xml)
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:sala_test;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=

# Configurações do Hibernate para o H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.format-sql=false